spring.application.name=spring-data-rest-

spring.datasource.url=jdbc:postgresql://localhost:5432/unytech
spring.datasource.username=postgres
spring.datasource.password=Yannam@57
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
